#!/bin/sh
docker_prune() {
	docker system prune --volumes -fa
}

alias d=docker
alias dps='docker ps'
alias dpsa='docker ps -a'
alias dimages='docker images'
alias dlogs='docker logs'
alias dexec='docker exec'
alias dstop='docker stop'
alias drm='docker rm'
alias drmfa='docker rm -f'
alias drmfaa='docker rm -f $(docker ps -a -q)'
alias drmi='docker rmi'
alias drmiid='docker rmi -f'
alias drmiida='docker rmi -f $(docker images -a -q)'
alias dprune='docker_prune'
alias dprunev='docker system prune --volumes -fa'
alias dprunef='docker system prune --force'
alias dprunefv='docker system prune --volumes --force'
alias dprunefva='docker system prune --volumes --force --all'
alias dprunefvai='docker system prune --volumes --force --all --filter "until=24h"'
alias dprunefvaii='docker system prune --volumes --force --all --filter "until=48h"'
alias dprunefvaiii='docker system prune --volumes --force --all --filter "until=72h"'
alias dprunefvaiiii='docker system prune --volumes --force --all --filter "until=96h"'

alias dc='docker-compose'
alias dcb='docker-compose build'
alias dcbf='docker-compose build --force-rm'
alias dcu='docker-compose up'
alias dcud='docker-compose up -d'
alias dcudb='docker-compose up -d --build'
alias dcudbf='docker-compose up -d --build --force-recreate'
alias dcudf='docker-compose up -d --force-recreate'
alias dcudr='docker-compose up -d --remove-orphans'
alias dcudrb='docker-compose up -d --remove-orphans --build'
alias dcudrbf='docker-compose up -d --remove-orphans --build --force-recreate'
alias dcudrf='docker-compose up -d --remove-orphans --force-recreate'
alias dcudt='docker-compose up -d --timeout 60'
alias dcudtb='docker-compose up -d --timeout 60 --build'
alias dcudtbf='docker-compose up -d --timeout 60 --build --force-recreate'
alias dcudtf='docker-compose up -d --timeout 60 --force-recreate'
alias dcudtr='docker-compose up -d --timeout 60 --remove-orphans'
alias dcudtrb='docker-compose up -d --timeout 60 --remove-orphans --build'
alias dcudtrbf='docker-compose up -d --timeout 60 --remove-orphans --build --force-recreate'
alias dcudtrf='docker-compose up -d --timeout 60 --remove-orphans --force-recreate'
alias dcuf='docker-compose up --force-recreate'
alias dcufb='docker-compose up --force-recreate --build'

alias dcd='docker-compose down'
alias dcdt='docker-compose down --timeout 60'
alias dcdtr='docker-compose down --timeout 60 --remove-orphans'
alias dcdtrv='docker-compose down --timeout 60 --remove-orphans --volumes'
alias dcdv='docker-compose down --volumes'
alias dcdvr='docker-compose down --volumes --remove-orphans'
alias dcdvrt='docker-compose down --volumes --remove-orphans --timeout 60'
alias dcr='docker-compose restart'
alias dcrd='docker-compose restart -d'
alias dcrdt='docker-compose restart -d --timeout 60'
alias dcrf='docker-compose restart --force-recreate'
alias dcrfb='docker-compose restart --force-recreate --build'
alias dcrfd='docker-compose restart --force-recreate -d'
alias dcrfdb='docker-compose restart --force-recreate -d --build'
alias dcrfdt='docker-compose restart --force-recreate -d --timeout 60'
alias dcrfdtb='docker-compose restart --force-recreate -d --timeout 60 --build'

alias dcs='docker-compose start'
alias dcsd='docker-compose start -d'
alias dcsdt='docker-compose start -d --timeout 60'
alias dcsf='docker-compose start --force-recreate'
alias dcsfb='docker-compose start --force-recreate --build'
alias dcsfd='docker-compose start --force-recreate -d'
alias dcsfdb='docker-compose start --force-recreate -d --build'
alias dcsfdt='docker-compose start --force-recreate -d --timeout 60'
alias dcsfdtb='docker-compose start --force-recreate -d --timeout 60 --build'

alias dce='docker-compose exec'
alias dcei='docker-compose exec -it'
alias dceib='docker-compose exec -it --user root'
alias dceibash='docker-compose exec -it --user root bash'
alias dceibashc='docker-compose exec -it --user root bash -c'
alias dceibashs='docker-compose exec -it --user root bash -s'
alias dceibashsc='docker-compose exec -it --user root bash -sc'
alias dceibashscd='docker-compose exec -it --user root bash -scd'
alias dceibashscdls='docker-compose exec -it --user root bash -scd "ls -lah"'
alias dceibashscdlsd='docker-compose exec -it --user root bash -scd "ls -lah /data"'
alias dceibashscdlsdd='docker-compose exec -it --user root bash -scd "ls -lah /data/data"'
